### PR TITLE
Adjust the API Document headers to make them consistent

### PR DESCRIPTION
**Pull request by stefafafan**
## What I have done
- Some headers are in the form, `List of...` , or `Get list of ...`, and others are in the form, `Listing ...`
  - I prefer the latter so I am going through the API list and replacing the titles to make them consistent.

For headers I mean here,
https://mackerel.io/api-docs/

スクリーンショット 2020-01-06 22 52 18

And here (the individual pages)
https://mackerel.io/api-docs/entry/services
スクリーンショット 2020-01-06 22 52 30

## Reviewing the Pull Request
- The diff is kind of big (sorry), so maybe it is easier to check the diff for each commit.

### CODE REVIEW

**Comment by a-know** [comment]
LGTM. Thanks!!

**Comment by stefafafan** [comment]
@a-know Thank you for the review as well as merging/publishing.

I noticed that the sidebar is still old, is this part updated separately from this repository?
https://mackerel.io/api-docs/entry/services

キャプチャ

**Comment by a-know** [comment]
@stefafafan 
Thank you for pointing that out!

As for the sidebar, it is the part where code management is not possible. So I will fix it. Please wait...

**Comment by a-know** [comment]
@stefafafan 
Completed the sidebar fix. Can you check it?

**Comment by stefafafan** [comment]
@a-know I just checked it out, looks good!
Thank you very much. 😄

**Pull request merged**
